export const options = [
    { label: "Conferences", value: "conferences" },
    { label: "Seminars", value: "seminars" },
    { label: "Product Launches", value: "product_launches" },
    { label: "Team Building Events", value: "team_building" },
    { label: "Networking Events", value: "networking_events" },
    { label: "Trade Shows", value: "trade_shows" },
    { label: "Executive Retreats", value: "executive_retreats" },
    { label: "Workshops", value: "workshops" },
    { label: "Webinars", value: "webinars" },
    { label: "Weddings", value: "weddings" },
    { label: "Birthdays", value: "birthdays" },
    { label: "Anniversaries", value: "anniversaries" },
    { label: "Family Reunions", value: "family_reunions" },
    { label: "Graduation Parties", value: "graduation_parties" },
    { label: "Baby Showers", value: "baby_showers" },
    { label: "Retirement Parties", value: "retirement_parties" },
    { label: "Engagement Parties", value: "engagement_parties" },
    { label: "Housewarming Parties", value: "housewarming_parties" },
    { label: "Festivals and Fairs", value: "festivals_fairs" },
    { label: "Parades", value: "parades" },
    { label: "Street Fairs", value: "street_fairs" },
    { label: "Charity Events", value: "charity_events" },
    { label: "Public Lectures", value: "public_lectures" },
    { label: "Religious Gatherings", value: "religious_gatherings" },
    { label: "Food and Wine Festivals", value: "food_wine_festivals" },
    { label: "Cultural Events", value: "cultural_events" },
    { label: "School Fairs", value: "school_fairs" },
    { label: "Graduation Ceremonies", value: "graduation_ceremonies" },
    { label: "Alumni Events", value: "alumni_events" },
    { label: "Competitions", value: "competitions" },
    { label: "Career Fairs", value: "career_fairs" },
    { label: "Open Houses", value: "open_houses" },
    {
      label: "Concerts and Music Festivals",
      value: "concerts_music_festivals",
    },
    { label: "Comedy Shows", value: "comedy_shows" },
    { label: "Art Exhibitions", value: "art_exhibitions" },
    { label: "Movie Screenings", value: "movie_screenings" },
    { label: "Sports Events", value: "sports_events" },
    { label: "Theater Performances", value: "theater_performances" },
    { label: "Game Nights", value: "game_nights" },
    { label: "Charity Auctions", value: "charity_auctions" },
    { label: "Gala Dinners", value: "gala_dinners" },
    { label: "Benefit Concerts", value: "benefit_concerts" },
    { label: "Walkathons", value: "walkathons" },
    { label: "Bake Sales", value: "bake_sales" },
    { label: "Raffles", value: "raffles" },
    { label: "Silent Auctions", value: "silent_auctions" },
    { label: "Online Conferences", value: "online_conferences" },
    { label: "Virtual Trade Shows", value: "virtual_trade_shows" },
    { label: "Online Social Gatherings", value: "online_social_gatherings" },
    { label: "Live Streams", value: "live_streams" },
    { label: "Leadership Summits", value: "leadership_summits" },
    { label: "Skill-building Workshops", value: "skill_building_workshops" },
    { label: "Mentorship Programs", value: "mentorship_programs" },
    { label: "Coaching Sessions", value: "coaching_sessions" },
    { label: "Certification Courses", value: "certification_courses" },
    { label: "Networking Mixers", value: "networking_mixers" },
    { label: "Campaign Rallies", value: "campaign_rallies" },
    { label: "Debates and Town Halls", value: "debates_town_halls" },
    { label: "Protests", value: "protests" },
    { label: "Public Forums", value: "public_forums" },
    {
      label: "Community Planning Meetings",
      value: "community_planning_meetings",
    },
    { label: "Policy Briefings", value: "policy_briefings" },
    { label: "Hackathons", value: "hackathons" },
    { label: "Coding Bootcamps", value: "coding_bootcamps" },
    { label: "Tech Meetups", value: "tech_meetups" },
    { label: "Open-source Sprints", value: "open_source_sprints" },
    { label: "Tech Panel Discussions", value: "tech_panel_discussions" },
  ];

